#!/bin/bash -e

. /dev/shm/cron-environment

if [[ -n "$TRIGGER_URL" ]]; then
  chpst -u nobody:nogroup /usr/bin/curl --output /dev/null --silent -H "Content-Type: application/json" --data '{"build": true}' -X POST ${TRIGGER_URL}
fi
